<?php
$lista_frases = [
    '01'=> "Todavia é preciso pedir com fé, sem duvidar, porque aquele que duvida é como a onda do mar, que o vento leva de um lado para outro. Tiago 1:6",
    '02'=> "Conhecendo Jesus seus pensamentos, disse-lhes: por que vocês pensam maldosamente em seu coração? Mateus 9:4",
    '03'=> "Finalmente, fortaleçam-se no Senhor e no seu forte poder. Efésios 6:10",
    '04'=> "Louvai ao SENHOR, porque é bom cantar louvores ao nosso Deus, porque é agradável; decoroso é o louvor.  Salmos 147:1",
    '05'=> "Maria, porém, guardava todas essas coisas e sobre elas refletia em seu coração. Lucas 2:19 ",
    '06'=> "Procurai a paz com todos e ao mesmo tempo a santidade, sem a qual ninguém pode ver o Senhor. Hebreus 12:14 ",
    '07'=> "Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que não se veem. Hebreus 11:1 ",
    '08'=> "E eu pedirei ao Pai, e ele dará a vocês outro Conselheiro para estar com vocês para sempre. João 14:16 ",
    '09'=> "Ao contrário, sua satisfação está na lei do Senhor, e nessa lei medita dia e noite. Salmos 1:2 ",
    '10'=> "Basta-te minha graça, porque é na fraqueza que se revela totalmente a minha força. Portanto, prefiro gloriar-me das minhas fraquezas, para que habite em mim a força de Cristo. 2 Coríntios 12:9a ",
    '11'=> "Esperança que tarda deixa doente o coração; desejo que se realiza é árvore de vida. Provérbios 13:12 ",
    '12'=> "O Senhor conhece os pensamentos do homem, e sabe como são fúteis. Salmos 94:11 ",
    '13'=> "Não entregues tua alma à tristeza, não atormentes a ti mesmo em teus pensamentos. A alegria do coração é a vida do homem, e um inesgotável tesouro de santidade. Eclesiástico 30:22 ",
    '14'=> "Apeguemo-nos com firmeza à esperança que professamos, pois, aquele que prometeu é fiel. Hebreus 10:23 ",
    '15'=> "O meu Deus suprirá todas as necessidades de vocês, de acordo com as suas gloriosas riquezas em Cristo Jesus. Filipenses 4:19 ",
    '16'=> "Quando eu era menino, falava como menino, pensava como menino e raciocinava como menino. Quando me tornei homem, deixei para trás as coisas de menino. 1 Coríntios 13:11 ",
    '17'=> "A tua palavra é lâmpada que ilumina os meus passos e luz que clareia o meu caminho. Salmos 119:105 ",
    '18'=> "Àquele que é capaz de fazer infinitamente mais do que tudo o que pedimos ou pensamos, de acordo com o seu poder que atua em nós, Efésios 3:20 ",
    '19'=> "Sejam alegres na esperança, pacientes na tribulação e perseverantes na oração. Romanos 12:12 ",
    '20'=> "Sejam todos humildes uns para com os outros, porque Deus se opõe aos orgulhosos, mas concede graça aos humildes. 1 Pedro 5:5 ",
    '21'=> "O Senhor detesta os pensamentos dos maus, mas se agrada de palavras ditas sem maldade. Provérbios 15:26 ",
    '22'=> "Isto é uma ordem: sê firme e corajoso. Não te atemorizes, não tenhas medo, porque o Senhor está contigo em qualquer parte para onde fores. Josué 1, 9 ",
    '23'=> "Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque Tu estás comigo. Salmos 23:4 ",
    '24'=> "Quando me deito, lembro-me de ti; penso em ti durante as vigílias da noite. Salmos 63:6 ",
    '25'=> "Os planos bem elaborados levam à fartura; mas o apressado sempre acaba na miséria. Provérbios 21:5 ",
    '26'=> "Mantenham o pensamento nas coisas do alto, e não nas coisas terrenas. Colossenses 3:2 ",
    '27'=> "Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus; não por obras, para que ninguém se glorie. Efésios 2:8-9 ",
    '28'=> "Sem fé é impossível agradar a Deus, pois quem d'Ele se aproxima precisa crer que Ele existe e que recompensa aqueles que o buscam. Hebreus 11:6 ",
    '29'=> "Além disso, usem o escudo da fé, com o qual vocês poderão apagar todas as setas inflamadas do maligno. Efésios 6:16 ",
    '30'=> "Deem graças ao Senhor porque ele é bom; o Seu amor dura para sempre. Salmos 107:1 ",
    '31'=> "Acima de tudo, porém, revistam-se do amor, que é o elo perfeito. Colossenses 3:14 ",
    ];

?>